### ISSUE TITLE
Opens demo pages

### ISSUE THREAD

**Issue by iggy** [SteamWo1f/ranlab#6]
Often enough a demo site opens with no idea what the site is a demo of or how to use it.

A bad example (it was just the last one that opened) is https://demo.homarr.dev/start-demo I could at least google what homarr was to figure out what was going on, but there were some other examples that I had no idea what was going on.

Other examples:
https://word-mastermind.glitch.me/

Awesome project btw, I already found and installed a tool that I wouldn't have found otherwise (stirling pdf).

**Comment by SteamWo1f** [comment]
The quickest solution I have to help you is to change the drop-down choice from `main link` to `source code link`. This should prevent random demo pages from opening when clicking the button.

The reason why this issue occurs is because ranlab scans through awesome-selfhosted's readme and uses the first link associated with the title, for example: `[CoolArchive](demo.coolarchive.example.org)`. If it selects "CoolArchive", it would direct you to "demo.coolarchive.example.org". It does not check if it is a demo page or a normal homepage.

The `source code link` option functions differently because ranlab searches for the text "source code" and utilizes that link, which should direct you to the repository of the project rather than any other link associated with the project's name in the awesome-selfhosted readme
